### ISSUE TITLE
Compatibility with vue/reactivity 3.5

### ISSUE THREAD

**Issue by moussaclarke** [antfu/vue-reactivity-watch#8]
It seems that this library no longer works from vue/reactivity 3.5.0 and up - haven't really dug into why as yet, but I'm guessing some kind of breaking change upstream.

Minimal repro (with vue/reactivity 3.5.12)
https://stackblitz.com/edit/vitejs-vite-umcrtp?file=package.json

Click on the counter - nothing happens.

Working version with vue/reactivity 3.4.38 with same code for comparison
https://stackblitz.com/edit/vitejs-vite-yuzqjo?file=package.json

Click on the counter - count increments as expected

**Comment by antfu** [comment]
You don't need this library in 3.5 anymore. Vue 3.5 exposes watch from the reactivity package now.

**Comment by moussaclarke** [comment]
Well that definitely makes things simpler going forward :smile: Will remove the dependency in that case.

Thanks for the package, and for your response!

**Comment by moussaclarke** [comment]
Closing as package is no longer needed as per comment above
